In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [3]:
pd.set_option("display.max_column",None)
pd.set_option("display.max_rows",100)
pd.set_option("display.max_colwidth",None)

In [4]:
data_path = "../data/"

orders = pd.read_csv(data_path + "olist_orders_dataset.csv")
customers = pd.read_csv(data_path + "olist_customers_dataset.csv")
order_item = pd.read_csv(data_path + "olist_order_items_dataset.csv")
product = pd.read_csv(data_path + "olist_products_dataset.csv")
payments = pd.read_csv(data_path + "olist_order_payments_dataset.csv")
reviews = pd.read_csv(data_path + "olist_order_reviews_dataset.csv")
sellers = pd.read_csv(data_path + "olist_sellers_dataset.csv")
geolocation = pd.read_csv(data_path + "olist_geolocation_dataset.csv")
category_translation = pd.read_csv(
    data_path + "product_category_name_translation.csv"
)

In [5]:
datasets={
    "orders":orders,
    "customers":customers,
    "order_item":order_item,
    "product":product,
     "payments":payments,
     "reviews":reviews,
     "sellers":sellers,
     "geolocation":geolocation,
     "category_translation":category_translation
}



for name ,df in datasets.items():
    print("\n"+"="*50)
    print(name.upper())
    print("="*50)

    print(df.isnull().sum())

==================================================
ORDERS
==================================================
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

==================================================
CUSTOMERS
==================================================
customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

==================================================
ORDER_ITEM
==================================================
order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

==================================================
PRODUCT
==================================================
product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

==================================================
PAYMENTS
==================================================
order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

==================================================
REVIEWS
==================================================
review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

==================================================
SELLERS
==================================================
seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

==================================================
GEOLOCATION
==================================================
geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

==================================================
CATEGORY_TRANSLATION
==================================================
product_category_name            0
product_category_name_english    0
dtype: int64

In [6]:
pd.crosstab(
    orders["order_status"],
    orders["order_delivered_customer_date"].isnull())

order_delivered_customer_date  False  True
order_status
approved                           0      2
canceled                           6    619
created                            0      5
delivered                      96470      8
invoiced                           0    314
processing                         0    301
shipped                            0   1107
unavailable                        0    609

In [7]:
orders[
    (orders["order_status"]=="delivered") &
        (orders["order_delivered_customer_date"].isnull())
].T

,3002,20618,43834,79263,82868,92643,97647,98038
order_id,2d1e2d5bf4dc7227b3bfebb81328c15f,f5dd62b788049ad9fc0526e3ad11a097,2ebdfc4f15f23b91474edf87475f108e,e69f75a717d64fc5ecdfae42b2e8e086,0d3268bad9b086af767785e3f0fc0133,2d858f451373b04fb5c984a1cc2defaf,ab7c89dc1bf4a1ead9d6ec1ec8968a84,20edc82cf5400ce95e1afacc25798b31
customer_id,ec05a6d8558c6455f0cbbd8a420ad34f,5e89028e024b381dc84a13a3570decb4,29f0540231702fda0cfdee0a310f11aa,cfda40ca8dd0a5d486a9635b611b398a,4f1d63d35fb7c8999853b2699f5c7649,e08caf668d499a6d643dafd7c5cc498a,dd1b84a7286eb4524d52af4256c0ba24,28c37425f1127d887d7337f284080a0f
order_status,delivered,delivered,delivered,delivered,delivered,delivered,delivered,delivered
order_purchase_timestamp,2017-11-28 17:44:07,2018-06-20 06:58:43,2018-07-01 17:05:11,2018-07-01 22:05:55,2018-07-01 21:14:02,2017-05-25 23:22:43,2018-06-08 12:09:39,2018-06-27 16:09:12
order_approved_at,2017-11-28 17:56:40,2018-06-20 07:19:05,2018-07-01 17:15:12,2018-07-01 22:15:14,2018-07-01 21:29:54,2017-05-25 23:30:16,2018-06-08 12:36:39,2018-06-27 16:29:30
order_delivered_carrier_date,2017-11-30 18:12:23,2018-06-25 08:05:00,2018-07-03 13:57:00,2018-07-03 13:57:00,2018-07-03 09:28:00,NaN,2018-06-12 14:10:00,2018-07-03 19:26:00
order_delivered_customer_date,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
order_estimated_delivery_date,2017-12-18 00:00:00,2018-07-16 00:00:00,2018-07-30 00:00:00,2018-07-30 00:00:00,2018-07-24 00:00:00,2017-06-23 00:00:00,2018-06-26 00:00:00,2018-07-19 00:00:00

In [8]:
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [9]:
date_columns =["order_delivered_carrier_date","order_delivered_customer_date",
 "order_estimated_delivery_date","order_purchase_timestamp","order_approved_at"]

for col in date_columns:
    orders[col]=pd.to_datetime(orders[col],errors="coerce")

In [10]:
orders[date_columns].dtypes

order_delivered_carrier_date     datetime64[us]
order_delivered_customer_date    datetime64[us]
order_estimated_delivery_date    datetime64[us]
order_purchase_timestamp         datetime64[us]
order_approved_at                datetime64[us]
dtype: object

In [11]:
orders.duplicated().sum()

np.int64(0)

In [12]:
orders["order_id"].duplicated().sum()

np.int64(0)

In [13]:
orders.dtypes

order_id                                    str
customer_id                                 str
order_status                                str
order_purchase_timestamp         datetime64[us]
order_approved_at                datetime64[us]
order_delivered_carrier_date     datetime64[us]
order_delivered_customer_date    datetime64[us]
order_estimated_delivery_date    datetime64[us]
dtype: object

In [14]:
(orders["order_approved_at"]<orders["order_purchase_timestamp"]).sum()

np.int64(0)

In [15]:
(orders["order_delivered_carrier_date"]<orders["order_approved_at"]).sum()

np.int64(1359)

In [16]:
orders[orders["order_delivered_carrier_date"]<orders["order_approved_at"]][["order_id","order_delivered_carrier_date","order_delivered_customer_date",
 "order_estimated_delivery_date","order_purchase_timestamp","order_approved_at"]].head()

,order_id,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_purchase_timestamp,order_approved_at
15,dcb36b511fcac050b97cd5c05de84dc3,2018-06-11 14:54:00,2018-06-21 15:34:32,2018-07-04,2018-06-07 19:03:12,2018-06-12 23:31:02
64,688052146432ef8253587b930b01a06d,2018-04-23 19:19:14,2018-04-24 19:31:58,2018-05-15,2018-04-22 08:48:13,2018-04-24 18:25:22
199,58d4c4747ee059eeeb865b349b41f53a,2018-07-24 12:57:00,2018-07-25 23:58:19,2018-07-31,2018-07-21 12:49:32,2018-07-26 23:31:53
210,412fccb2b44a99b36714bca3fef8ad7b,2018-07-23 12:24:00,2018-07-24 19:26:42,2018-07-31,2018-07-22 22:30:05,2018-07-23 12:31:53
415,56a4ac10a4a8f2ba7693523bb439eede,2018-07-24 14:03:00,2018-07-28 00:05:39,2018-08-06,2018-07-22 13:04:47,2018-07-27 23:31:09

In [17]:
invalid_approval=(
    orders["order_approved_at"]<orders["order_purchase_timestamp"]
).sum()

invalid_carrier=(
    orders["order_delivered_carrier_date"]<orders["order_approved_at"]
).sum()

invalid_delivery=(
  orders["order_delivered_customer_date"]<orders["order_delivered_carrier_date"]
).sum()


print("Approval Before purchase",invalid_approval)
print("Carried before Approval",invalid_carrier)
print("customer Delivery before carrier delivery",invalid_delivery)

Approval Before purchase 0
Carried before Approval 1359
customer Delivery before carrier delivery 23

In [18]:
orders["orders_sequence_valid"]=True
orders.loc[
             orders["order_approved_at"].notna() &
        (orders["order_approved_at"]<orders["order_purchase_timestamp"]),
         "orders_sequence_valid"
]=False

In [19]:
orders["orders_sequence_valid"].value_counts()

orders_sequence_valid
True    99441
Name: count, dtype: int64

In [20]:
orders.loc[
    orders["order_delivered_carrier_date"].notna() &
    orders["order_approved_at"].notna() &
    (orders["order_delivered_carrier_date"] < orders["order_approved_at"]),
    "orders_sequence_valid"
] = False

In [21]:
orders["orders_sequence_valid"].value_counts()

orders_sequence_valid
True     98082
False     1359
Name: count, dtype: int64

In [22]:
orders.loc[
    orders["order_delivered_customer_date"].notna() &
    orders["order_delivered_carrier_date"].notna() &
    (orders["order_delivered_customer_date"] < orders["order_delivered_carrier_date"]),
    "orders_sequence_valid"
] = False

In [23]:
orders["orders_sequence_valid"].value_counts()

orders_sequence_valid
True     98059
False     1382
Name: count, dtype: int64

In [24]:
orders.loc[
    orders["orders_sequence_valid"] == False,
    "order_status"
].value_counts()

order_status
delivered    1373
shipped         9
Name: count, dtype: int64

In [25]:
orders['delivery_time_valid'] = (
    orders['order_delivered_customer_date'].notna() &
    orders['order_delivered_carrier_date'].notna() &
    (
        orders['order_delivered_customer_date'] >=
        orders['order_delivered_carrier_date']
    )
)

orders['delivery_time_valid'].value_counts()

delivery_time_valid
True     96452
False     2989
Name: count, dtype: int64

In [26]:
orders["Total delevry time"]=(
    orders["order_delivered_customer_date"] - orders['order_delivered_carrier_date']
).dt.total_seconds()/(24*20*60)

In [27]:
orders['Total delevry time'].describe()

count    96475.000000
mean        27.991641
std         26.280365
min        -48.288507
25%         12.299844
50%         21.299306
75%         36.087344
max        615.572917
Name: Total delevry time, dtype: float64

In [28]:
orders[orders['Total delevry time'] < 0][
    [
        'order_id',
        'order_status',
        'order_delivered_carrier_date',
        'order_delivered_customer_date',
        'Total delevry time'
    ]
].head(10)

,order_id,order_status,order_delivered_carrier_date,order_delivered_customer_date,Total delevry time
6437,a1abeb653a4d4cd1e142ccb8c82cd069,delivered,2017-07-28 16:57:58,2017-07-25 19:32:56,-8.677153
9553,383aa8b2724fe452d9ccd9934a8c628b,delivered,2017-07-07 17:22:41,2017-07-06 14:27:51,-3.364236
13487,cb1134f9010d242e9515ad1c78ec0c39,delivered,2017-07-20 19:22:02,2017-07-19 14:13:28,-3.642847
14474,dceb62e8fa94b46006c9554fed743df0,delivered,2017-08-01 18:23:30,2017-07-26 18:09:10,-18.029861
19268,5f9d46795c3126674e52becb3a1a517f,delivered,2017-07-20 23:03:42,2017-07-20 18:52:41,-0.522951
21338,8c78d01de3a9009e23d6877a7cc9be20,delivered,2016-10-26 11:41:53,2016-10-25 17:51:46,-2.229410
22520,b27af682321527a6349f1761eb3f360c,delivered,2017-06-27 14:51:54,2017-06-26 15:45:35,-2.888160
25393,1cc3ae63caffff2d6c3ee3e78e074acf,delivered,2017-08-10 18:28:56,2017-08-10 18:05:38,-0.048542
25646,e37f11cae9985ca58f0b56f268720537,delivered,2017-08-01 18:17:47,2017-07-31 17:49:56,-3.058021
27470,fa3e37584f4fdb1ded0e0de700dfcb4e,delivered,2017-08-09 18:18:43,2017-08-01 21:13:01,-23.636875

In [29]:
orders.loc[orders['Total delevry time'] < 0, 'Total delevry time'] = np.nan

In [30]:
orders['Total delevry time'].describe()

count    96452.000000
mean        28.000654
std         26.276474
min          0.000000
25%         12.304575
50%         21.300937
75%         36.091328
max        615.572917
Name: Total delevry time, dtype: float64

In [31]:
orders[orders['Total delevry time'] > 100][
    [
        'order_id',
        'order_status',
        'order_delivered_carrier_date',
        'order_delivered_customer_date',
        'Total delevry time'
    ]
].sort_values('Total delevry time', ascending=False).head(20)

,order_id,order_status,order_delivered_carrier_date,order_delivered_customer_date,Total delevry time
55619,1b3190b2dfa9d789e1f14c05b647a14a,delivered,2018-02-26 18:49:07,2018-09-19 23:24:07,615.572917
19590,ca07593549f1816d26a572e06dc1eab6,delivered,2017-03-08 13:47:46,2017-09-19 14:36:39,585.101840
89130,285ab9426d6982034523a855f55a885e,delivered,2017-03-09 08:53:20,2017-09-19 14:00:04,582.639028
70307,2fb597c2f772eca01b1f5c561bf6cc7b,delivered,2017-03-13 08:54:02,2017-09-19 14:33:17,570.706771
61610,440d0d17af552815d15a9e41abe49359,delivered,2017-03-15 13:00:08,2017-09-19 15:12:50,564.276458
54480,2d7561026d542c8dbd8f0daeadf67a43,delivered,2017-03-16 09:29:16,2017-09-19 14:38:18,561.643819
81401,2fe324febf907e3ea3f2aa9650869fa5,delivered,2017-03-17 07:23:53,2017-09-19 17:00:07,559.200486
62286,437222e3fd1b07396f1d9ba8c15fba59,delivered,2017-03-21 08:22:43,2017-09-19 16:28:58,547.013021
68769,c27815f7e3dd0b926b58552628481575,delivered,2017-03-21 14:50:25,2017-09-19 17:14:25,546.300000
31228,dfe5f68118c2576143240b8d78e5940a,delivered,2017-03-21 18:28:04,2017-09-19 18:13:19,545.969271
38509,0f4519c5f1c541ddec9f21b3bddd533a,delivered,2017-03-22 05:28:14,2017-09-19 14:38:21,544.146076
74117,6e82dcfb5eada6283dba34f164e636f5,delivered,2017-05-19 10:57:36,2017-11-16 10:56:45,542.998229
66407,2ba1366baecad3c3536f27546d129017,delivered,2017-03-02 18:03:45,2017-08-28 16:23:46,536.791701
25883,7c48bb55e8e4f7e56d412e9653db37bc,delivered,2018-01-26 13:35:00,2018-07-23 20:04:45,534.811979
64489,3566eabb132f8d64741ae7b921bbd10e,delivered,2017-03-30 16:09:39,2017-09-19 15:07:09,518.869792
40847,d24e8541128cea179a11a65176e0a96f,delivered,2017-06-16 14:44:37,2017-12-04 18:36:29,513.483056
74759,2fa29503f2ebd9f53deba187160f3202,delivered,2017-04-03 14:35:57,2017-09-19 18:24:46,507.476701
86520,ed8e9faf1b75f43ee027103957135663,delivered,2017-12-04 19:48:46,2018-05-21 18:22:18,503.819861
69171,525e11b26fdb7f41471d289897d0f6da,delivered,2017-04-05 14:44:29,2017-09-19 14:58:10,501.028507
37973,df6d8b7768a047c2981bae0a24afbb01,delivered,2017-04-05 15:24:20,2017-09-19 15:08:19,500.966632

In [32]:
orders[orders['Total delevry time'] > 100].shape

(1996, 11)

In [33]:
orders[orders['Total delevry time'] > 100]['Total delevry time'].count()

np.int64(1996)

In [34]:
orders['Total delevry time'].quantile([0.90, 0.95, 0.99, 0.995, 0.999])

0.900     56.706799
0.950     72.632033
0.990    122.954340
0.995    146.626243
0.999    230.894474
Name: Total delevry time, dtype: float64

In [35]:
orders['delivery_time_clean'] = orders['Total delevry time'].where(
    orders['Total delevry time'] <= 200
)

In [36]:
orders['delivery_time_clean'].describe()

count    96293.000000
mean        27.544699
std         23.307915
min          0.000000
25%         12.294688
50%         21.288125
75%         36.034340
max        199.823507
Name: delivery_time_clean, dtype: float64

In [37]:
orders.isna().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
orders_sequence_valid               0
delivery_time_valid                 0
Total delevry time               2989
delivery_time_clean              3148
dtype: int64

In [38]:
orders.rename(
    columns={'Total delevry time': 'total_delivery_time'},
    inplace=True
)

Customers

In [39]:
customers.duplicated().sum()

np.int64(0)

In [40]:
customers.dtypes

customer_id                   str
customer_unique_id            str
customer_zip_code_prefix    int64
customer_city                 str
customer_state                str
dtype: object

In [41]:
customers["customer_unique_id"].duplicated().sum()

np.int64(3345)

In [42]:
customers["customer_id"].duplicated().sum()

np.int64(0)

In [43]:
customers.duplicated().sum()

np.int64(0)

In [44]:
customers.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [45]:
customers.shape

(99441, 5)

In [46]:
customers["customer_id"].nunique()

99441

In [47]:
print(len(customers))
print("unique",customers.nunique())
print("duplicate",customers.duplicated().sum())

99441
unique customer_id                 99441
customer_unique_id          96096
customer_zip_code_prefix    14994
customer_city                4119
customer_state                 27
dtype: int64
duplicate 0

In [48]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  str
 1   customer_unique_id        99441 non-null  str
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  str
 4   customer_state            99441 non-null  str
dtypes: int64(1), str(4)
memory usage: 3.8 MB

ORDER ITEMS

In [49]:
order_item.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [50]:
order_item.tail()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79

In [51]:
order_item.info()

<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  str
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  str
 3   seller_id            112650 non-null  str
 4   shipping_limit_date  112650 non-null  str
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), str(4)
memory usage: 6.0 MB

In [52]:
order_item.shape

(112650, 7)

In [53]:
order_item.isnull().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [54]:
order_item.duplicated(subset=["order_id","order_item_id"]).sum()

np.int64(0)

In [55]:
order_item[["price","freight_value"]].sum()

price            13591643.70
freight_value     2251909.54
dtype: float64

In [56]:
(order_item["price"]<0).sum()

np.int64(0)

In [57]:
(order_item["freight_value"]<0).sum()

np.int64(0)

In [58]:
order_item.describe()

       order_item_id          price  freight_value
count  112650.000000  112650.000000  112650.000000
mean        1.197834     120.653739      19.990320
std         0.705124     183.633928      15.806405
min         1.000000       0.850000       0.000000
25%         1.000000      39.900000      13.080000
50%         1.000000      74.990000      16.260000
75%         1.000000     134.900000      21.150000
max        21.000000    6735.000000     409.680000

In [59]:
order_item["order_item_id"].value_counts().sort_index()

order_item_id
1     98666
2      9803
3      2287
4       965
5       460
6       256
7        58
8        36
9        28
10       25
11       17
12       13
13        8
14        7
15        5
16        3
17        3
18        3
19        3
20        3
21        1
Name: count, dtype: int64

Product

In [60]:
product.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [61]:
product.tail()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
32946,a0b7d5a992ccda646f2d34e418fff5a0,moveis_decoracao,45.0,67.0,2.0,12300.0,40.0,40.0,40.0
32947,bf4538d88321d0fd4412a93c974510e6,construcao_ferramentas_iluminacao,41.0,971.0,1.0,1700.0,16.0,19.0,16.0
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,cama_mesa_banho,50.0,799.0,1.0,1400.0,27.0,7.0,27.0
32949,83808703fc0706a22e264b9d75f04a2e,informatica_acessorios,60.0,156.0,2.0,700.0,31.0,13.0,20.0
32950,106392145fca363410d287a815be6de4,cama_mesa_banho,58.0,309.0,1.0,2083.0,12.0,2.0,7.0

In [62]:
product.duplicated().sum()

np.int64(0)

In [63]:
product.info()

<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  str
 1   product_category_name       32341 non-null  str
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), str(2)
memory usage: 2.3 MB

In [64]:
product["product_id"].duplicated().sum()

np.int64(0)

In [65]:
(product[["product_name_lenght","product_description_lenght","product_photos_qty",
         "product_weight_g","product_length_cm","product_height_cm","product_width_cm"]]<0).sum()

product_name_lenght           0
product_description_lenght    0
product_photos_qty            0
product_weight_g              0
product_length_cm             0
product_height_cm             0
product_width_cm              0
dtype: int64

In [66]:
product.describe()

,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
count,32341.000000,32341.000000,32341.000000,32949.000000,32949.000000,32949.000000,32949.000000
mean,48.476949,771.495285,2.188986,2276.472488,30.815078,16.937661,23.196728
std,10.245741,635.115225,1.736766,4282.038731,16.914458,13.637554,12.079047
min,5.000000,4.000000,1.000000,0.000000,7.000000,2.000000,6.000000
25%,42.000000,339.000000,1.000000,300.000000,18.000000,8.000000,15.000000
50%,51.000000,595.000000,1.000000,700.000000,25.000000,13.000000,20.000000
75%,57.000000,972.000000,3.000000,1900.000000,38.000000,21.000000,30.000000
max,76.000000,3992.000000,20.000000,40425.000000,105.000000,105.000000,118.000000

In [67]:
product["product_weight_g"].value_counts().head()

product_weight_g
200.0    2084
300.0    1561
150.0    1259
400.0    1206
100.0    1188
Name: count, dtype: int64

In [68]:
(product["product_weight_g"]==0).sum()

np.int64(4)

In [69]:
product.loc[product["product_weight_g"]==0]

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
9769,81781c0fed9fe1ad6e8c81fca1e1cb08,cama_mesa_banho,51.0,529.0,1.0,0.0,30.0,25.0,30.0
13683,8038040ee2a71048d4bdbbdc985b69ab,cama_mesa_banho,48.0,528.0,1.0,0.0,30.0,25.0,30.0
14997,36ba42dd187055e1fbe943b2d11430ca,cama_mesa_banho,53.0,528.0,1.0,0.0,30.0,25.0,30.0
32079,e673e90efa65a5409ff4196c038bb5af,cama_mesa_banho,53.0,528.0,1.0,0.0,30.0,25.0,30.0

In [70]:
product[product["product_weight_g"]==0][["product_id","product_weight_g","product_length_cm","product_height_cm","product_width_cm"]]

,product_id,product_weight_g,product_length_cm,product_height_cm,product_width_cm
9769,81781c0fed9fe1ad6e8c81fca1e1cb08,0.0,30.0,25.0,30.0
13683,8038040ee2a71048d4bdbbdc985b69ab,0.0,30.0,25.0,30.0
14997,36ba42dd187055e1fbe943b2d11430ca,0.0,30.0,25.0,30.0
32079,e673e90efa65a5409ff4196c038bb5af,0.0,30.0,25.0,30.0

In [71]:
product["product_weight_valid"]=product["product_weight_g"]>0

In [72]:
product["product_weight_valid"].value_counts()

product_weight_valid
True     32945
False        6
Name: count, dtype: int64

In [73]:
product["product_weight_g"]=product["product_weight_g"].replace(0,np.nan)

In [74]:
product["product_weight_g"].isna().sum()

np.int64(6)

In [75]:
product["product_weight_g"].describe()

count    32945.000000
mean      2276.748885
std       4282.225204
min          2.000000
25%        300.000000
50%        700.000000
75%       1900.000000
max      40425.000000
Name: product_weight_g, dtype: float64

In [76]:
(product[["product_name_lenght","product_description_lenght","product_photos_qty",
         "product_weight_g","product_length_cm","product_height_cm","product_width_cm"]]==0).sum()

product_name_lenght           0
product_description_lenght    0
product_photos_qty            0
product_weight_g              0
product_length_cm             0
product_height_cm             0
product_width_cm              0
dtype: int64

In [77]:
product.isna().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                6
product_length_cm               2
product_height_cm               2
product_width_cm                2
product_weight_valid            0
dtype: int64

In [78]:
product[product["product_category_name"].isna()].head(6)

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_weight_valid
105,a41e356c76fab66334f36de622ecbd3a,NaN,NaN,NaN,NaN,650.0,17.0,14.0,12.0,True
128,d8dee61c2034d6d075997acef1870e9b,NaN,NaN,NaN,NaN,300.0,16.0,7.0,20.0,True
145,56139431d72cd51f19eb9f7dae4d1617,NaN,NaN,NaN,NaN,200.0,20.0,20.0,20.0,True
154,46b48281eb6d663ced748f324108c733,NaN,NaN,NaN,NaN,18500.0,41.0,30.0,41.0,True
197,5fb61f482620cb672f5e586bb132eae9,NaN,NaN,NaN,NaN,300.0,35.0,7.0,12.0,True
244,e10758160da97891c2fdcbc35f0f031d,NaN,NaN,NaN,NaN,2200.0,16.0,2.0,11.0,True

In [79]:
product[
    product["product_height_cm"].isna()|
    product["product_length_cm"].isna()|
    product["product_width_cm"].isna()
]

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_weight_valid
8578,09ff539a621711667c43eba6a3bd8466,bebes,60.0,865.0,3.0,NaN,NaN,NaN,NaN,False
18851,5eb564652db742ff8f28759cd8d2652a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False

Order payments

In [80]:
payments.info()

<class 'pandas.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  str
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  str
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), str(2)
memory usage: 4.0 MB

In [81]:
payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [82]:
payments["order_id"].isna().sum()

np.int64(0)

In [83]:
(payments["payment_value"]<=0).sum()

np.int64(9)

In [84]:
payments[payments["payment_value"]<=0].head(9)

,order_id,payment_sequential,payment_type,payment_installments,payment_value
19922,8bcbe01d44d147f901cd3192671144db,4,voucher,1,0.0
36822,fa65dad1b0e818e3ccc5cb0e39231352,14,voucher,1,0.0
43744,6ccb433e00daae1283ccc956189c82ae,4,voucher,1,0.0
51280,4637ca194b6387e2d538dc89b124b0ee,1,not_defined,1,0.0
57411,00b1cb0320190ca0daa2c88b35206009,1,not_defined,1,0.0
62674,45ed6e85398a87c253db47c2d9f48216,3,voucher,1,0.0
77885,fa65dad1b0e818e3ccc5cb0e39231352,13,voucher,1,0.0
94427,c8c528189310eaa44a745b8d9d26908b,1,not_defined,1,0.0
100766,b23878b3e8eb4d25a158f57d96331b18,4,voucher,1,0.0

In [85]:
payments.duplicated().sum()

np.int64(0)

order reviews

In [86]:
reviews.info()

<class 'pandas.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  str
 1   order_id                 99224 non-null  str
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  str
 4   review_comment_message   40977 non-null  str
 5   review_creation_date     99224 non-null  str
 6   review_answer_timestamp  99224 non-null  str
dtypes: int64(1), str(6)
memory usage: 5.3 MB

In [87]:
reviews.isna().sum()

review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [88]:
reviews.duplicated().sum()

np.int64(0)

In [89]:
reviews["review_id"].duplicated().sum()

np.int64(814)

In [90]:
reviews["review_id"].nunique()

98410

In [93]:
reviews[reviews["review_id"].duplicated(keep=False)].head(20)

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
200,28642ce6250b94cc72bc85960aec6c62,e239d280236cdd3c40cb2c033f681d1c,5,NaN,NaN,2018-03-25 00:00:00,2018-03-25 21:03:02
344,a0a641414ff718ca079b3967ef5c2495,169d7e0fd71d624d306f132acd791cbe,5,NaN,NaN,2018-03-04 00:00:00,2018-03-06 20:12:53
346,f4d74b17cd63ee35efa82cd2567de911,f269e83a82f64baa3de97c2ebf3358f6,3,NaN,"A embalagem deixou a desejar, por pouco o produto não foi danificado, a caixa estava toda amassada.",2018-01-12 00:00:00,2018-01-13 18:46:10
360,ecbaf1fce7d2c09bfab46f89065afeaf,2451b9756f310d4cff5c7987b393870d,5,NaN,NaN,2017-07-27 00:00:00,2017-07-28 16:57:18
393,6b1de94de0f4bd84dfc4136818242faa,92acf87839903a94aeca0e5040d99acb,5,NaN,NaN,2018-02-16 00:00:00,2018-02-19 19:04:21
433,957011305e7a4b6c8a266eeeb8e0316d,54b4da510fed5dc3cf3e7a8e50a5f224,4,NaN,NaN,2018-03-10 00:00:00,2018-03-10 23:35:51
508,b34f4a786bf00b7c8486141ba482783b,b2501eb5c292d415f52576b3d4b5de74,3,NaN,NaN,2017-05-04 00:00:00,2017-05-22 12:02:34
661,d433c252647c51309432ca0b763f969b,448795135b904d057254f5fd0d5a6a4c,1,NaN,NaN,2017-09-03 00:00:00,2017-09-06 16:11:00
723,5f35bbde2b32b8617aab15b7a9a0ae24,ba568688e2f462d7c44a3fdc62e6456f,4,NaN,NaN,2017-11-26 00:00:00,2017-11-27 21:00:47
764,c5976a5a98e854fb23d7e03c6754ae60,2002ea16e75277eaa0b5d78632048540,5,NaN,NaN,2017-08-08 00:00:00,2017-08-10 11:11:29
778,62c7722239b976d943ec0d430cfe890e,1d297b4800ed1a3c5b0944d84c01ee99,3,NaN,NaN,2017-10-22 00:00:00,2017-10-31 15:33:32
795,ca8e5e40f55fbffaa631de686b627dde,bce7047b261dd5116e87384f4fe9afc1,5,NaN,NaN,2018-02-22 00:00:00,2018-02-23 17:32:41
834,6ec93e77f444e0b1703740a69122e35d,d8cbc79d1dd84f3c87cb2ca7663c930e,5,NaN,Vendedor compromisso do vou o cliente,2017-10-07 00:00:00,2017-10-07 19:47:11
841,ee9bde038f146b5ece0d9a859cc2a795,afb67c04593c89865f383745e2993cef,4,NaN,NaN,2017-12-21 00:00:00,2017-12-23 19:19:46
854,830636803620cdf8b6ffaf1b2f6e92b2,0176a6846bcb3b0d3aa3116a9a768597,5,NaN,NaN,2017-12-30 00:00:00,2018-01-02 10:54:06
911,43e5286eb9f62cabe4471ec1dff7142a,2de2a81f489e7ac7cc08d8e49dbd6c13,5,NaN,NaN,2017-11-04 00:00:00,2017-11-05 00:21:51
986,1f5aa5d7c3ee7895e4d223797b5a5f2d,c79bdf061e22288609201ec60deb42fb,5,NaN,Tudo ocorreu de forma eficiente,2017-05-10 00:00:00,2017-05-12 00:58:11
1009,3242cc306a9218d0377831e175d62fbf,711246846695fa895c1776f0ddc30b20,5,NaN,Ótimo,2017-07-21 00:00:00,2017-07-22 01:06:37
1153,1258a603cc9e4897f7955ab218c83b8c,4a4c3e1ff92b16c0ecf770b504693a88,3,NaN,NaN,2018-02-03 00:00:00,2018-02-03 23:43:14
1163,771654d19b26b9108952856b225ad105,4703440eb9289d3769819920e98ec061,5,NaN,NaN,2018-02-15 00:00:00,2018-02-16 01:50:41

In [92]:
reviews["review_score"].value_counts().sort_index()

review_score
1    11424
2     3151
3     8179
4    19142
5    57328
Name: count, dtype: int64

In [94]:
reviews[reviews["review_id"].duplicated(keep=False)]["review_id"].value_counts().head(10)

review_id
c444278834184f72b1484dfe47de7f97    3
308316408775d1600dad81bd3184556d    3
2d6ac45f859465b5c185274a1c929637    3
3415c9f764e478409e8e0660ae816dd2    3
4219a80ab469e3fc9901437b73da3f75    3
e44840754f12fad2b8646712121b349a    3
ddc52555ca27b0fe67d5255147682d2d    3
7b606b0d57b078384f0b58eac1d41d78    3
4d0e6dd087008d1f992d25ef6e1f619f    3
08528f70f579f0c830189efc523d2182    3
Name: count, dtype: int64

In [95]:
reviews[reviews["review_id"] == "c444278834184f72b1484dfe47de7f97"]

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
2952,c444278834184f72b1484dfe47de7f97,df56136b8031ecd28e200bb18e6ddb2e,5,NaN,NaN,2017-02-08 00:00:00,2017-02-14 13:58:48
43897,c444278834184f72b1484dfe47de7f97,566f53fc7d36fa366f7e221468121877,5,NaN,NaN,2017-02-08 00:00:00,2017-02-14 13:58:48
95774,c444278834184f72b1484dfe47de7f97,8557dabbdacec1a9e250f5e70afe1eab,5,NaN,NaN,2017-02-08 00:00:00,2017-02-14 13:58:48

In [96]:
sellers.info()

<class 'pandas.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   str
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   str
 3   seller_state            3095 non-null   str
dtypes: int64(1), str(3)
memory usage: 96.8 KB

In [97]:
sellers.duplicated().sum()

np.int64(0)

In [99]:
sellers["seller_id"].duplicated().sum()

np.int64(0)

In [100]:
sellers["seller_zip_code_prefix"].le(0).sum()

np.int64(0)

In [101]:
sellers["seller_city"].nunique()

611

In [102]:
sellers["seller_state"].nunique()

23

In [103]:
geolocation.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  str
 4   geolocation_state            1000163 non-null  str
dtypes: float64(2), int64(1), str(2)
memory usage: 38.2 MB

In [104]:
geolocation["geolocation_zip_code_prefix"].le(0).sum()

np.int64(0)

In [105]:
geolocation.duplicated().sum()

np.int64(261831)

In [106]:
((geolocation["geolocation_lat"] < -90) | (geolocation["geolocation_lat"] > 90)).sum()

np.int64(0)

In [107]:
((geolocation["geolocation_lng"] < -180) | (geolocation["geolocation_lng"] > 180)).sum()

np.int64(0)

In [108]:
category_translation.info()

<class 'pandas.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     str
 1   product_category_name_english  71 non-null     str
dtypes: str(2)
memory usage: 1.2 KB

In [109]:
category_translation.duplicated().sum()

np.int64(0)

In [110]:
category_translation.isnull().sum()

product_category_name            0
product_category_name_english    0
dtype: int64

In [112]:
customers.to_csv("../data/cleaned_customers.csv", index=False)
orders.to_csv("../data/cleaned_orders.csv", index=False)
order_item.to_csv("../data/cleaned_order_items.csv", index=False)
payments.to_csv("../data/cleaned_order_payments.csv", index=False)
reviews.to_csv("../data/cleaned_order_reviews.csv", index=False)
product.to_csv("../data/cleaned_products.csv", index=False)
sellers.to_csv("../data/cleaned_sellers.csv", index=False)
geolocation.to_csv("../data/cleaned_geolocation.csv", index=False)
category_translation.to_csv("../data/cleaned_translation.csv", index=False)